# Generated by Django 3.2.2 on 2021-07-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=30, verbose_name='Metodo De Pago')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='boletaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('detalle', models.CharField(max_length=300, verbose_name='Detalle Factura')),
                ('total_pedido', models.IntegerField(verbose_name='Total Pedido')),
                ('boleta_o_factura', models.CharField(max_length=30, verbose_name='Boleta O Factura')),
                ('formaPago_idpago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boleta.formapago')),
            ],
        ),
    ]
