# Generated by Django 3.2.2 on 2021-07-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalleServicio', '0003_alter_detalleservicio_fecha_pago'),
        ('Boleta', '0002_boletafactura_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletafactura',
            name='detalleServicio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detalleServicio.detalleservicio'),
        ),
    ]
