# Generated by Django 3.2.2 on 2021-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='hora_reserva',
            field=models.TimeField(verbose_name='Hora Reserva'),
        ),
    ]
