# Generated by Django 3.2.3 on 2021-05-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_reserva',
            field=models.DateTimeField(verbose_name='Fecha Reserva'),
        ),
    ]
