# Generated by Django 3.2.2 on 2021-05-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_ordenpedido_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidadpedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='cantidadpedido',
            name='id_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.detalleproducto'),
        ),
    ]
