# Generated by Django 3.2.2 on 2021-05-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20210525_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='id_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.ordenpedido'),
        ),
        migrations.DeleteModel(
            name='CantidadPedido',
        ),
    ]
