# Generated by Django 3.2.3 on 2021-06-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('pedidos', '0005_auto_20210529_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordenpedido',
            name='fecha_orden',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha_recepcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
