# Generated by Django 3.2.3 on 2021-06-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
    ]
