# Generated by Django 3.2.3 on 2021-06-03 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_usuario_activo_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
