# Generated by Django 3.2.2 on 2021-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
