# Generated by Django 3.2.2 on 2021-07-03 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('fecha_servicio', models.DateField(verbose_name='Fecha Servicio')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado Servicio')),
                ('id_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.reservaservicio')),
            ],
        ),
    ]
