# Generated by Django 3.2.2 on 2021-07-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('detalleServicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('id_detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalleServicio.detalleservicio')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Producto')),
            ],
        ),
    ]
