# Generated by Django 3.2.2 on 2021-07-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleServicio', '0002_productoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='fecha_pago',
            field=models.DateField(null=True, verbose_name='Fecha de Pago'),
        ),
    ]
