# Generated by Django 3.2.3 on 2021-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
